export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_INPUT = "SET_CURRENT_INPUT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const ADD_SEARCH_HISTORY = "ADD_SEARCH_HISTORY";
export const GET_SEARCH_HISTORY = "GET_SEARCH_HISTORY";
export const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY";
export const LOAD_SEARCH_DATABASE = "LOAD_SEARCH_DATABASE";
